---
title: "152section"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
library(survey)
```

```{r}
school<-read.csv("school.csv", header= TRUE, stringsAsFactors = FALSE)
ncol(school)
school$schid
summary(school$c0264)
table(school$c0264)
unique(school$ic0264)

school$c0174
factor(school$c0174)

data<-select(school,schid,vioinc08,c0174,c0176,c0178,c0180, c0264, finalwgt,strata)
colnames(data) = c("school_id", "num_vioninc", "prevention_train", "modification", "counseling", "mentor","train_drug","final_wt", "strata")
summary(data$modification)

data$prevention_train[data$prevention_train == 2]<-0
data$modification[data$modification == 2]<-0
data$counseling[data$counseling==2]<-0
data$mentor[data$mentor == 2] <- 0

summary(data)
nrow(data)
head(data)
data$final_wt
range(data$final_wt)
max(data$final_wt)
boxplot(data$final_wt, plot=FALSE)$out


school$inc_level <- cut(school$vioinc08,
  breaks = quantile(school$vioinc08, c(0, 0.25,0.75, 1)),
  labels = c("1", "2", "3"),
  right  = FALSE,
  include.lowest = TRUE
)




```



```{r}
svyboxplot( log(num_vioninc+2.7)~as.factor(prevention_train), dstrat, all.outliers = TRUE)
svyboxplot( log(num_vioninc+2.7)~as.factor(modification), dstrat, all.outliers = TRUE)
svyboxplot(log(num_vioninc+2.7)~as.factor(counseling), dstrat, all.outliers = TRUE)
svyboxplot( log(num_vioninc+2.7)~as.factor(mentor), dstrat, all.outliers = TRUE)
```

```{r}
svyboxplot( log(num_vioninc+2.7)~as.factor(train_drug), dstrat, all.outliers = TRUE)

ggplot(data, aes(x=as.factor(train_drug), y = log(num_vioninc + 2.7))) +
  geom_boxplot() + ggtitle("Teach or Train Students") +
  xlab("Teach or Train Students") + ylab("# of Incidents")
```



#deal with replicated weight
```{r}
summary(school)
rep_design <- svrepdesign(variables = school[,-c(201:251)],
                          repweights = school[, 202:251],
                          weights = school[,201],
                          combined.weights = TRUE,
                          type = "JKn", scale = 1, rscales = 1)
svymean(~vioinc08, rep_design)
#subset rows which are only middle schools and high school 
new_design <- subset(rep_design, strata>200 & strata<400) 
svymean(~vioinc08, new_design)


####try <- subset(rep_design, strata>200 & strata < 400, )

#run subset on the desgin
#type = "JKn" is jacknife

# do svyglm() on the new_design
svyglm(vioinc08 ~ c0174 + c0176 + c0178 +c0180 + c0264, new_design)

rep_design

svytotal(school$vioinc08, rep_design)
svymean(school$vioinc08, rep_design)


which(colnames(school) == "finalwgt")
which(colnames(school) == "repwgt50")



# ?update() for adding a new variable. 


#proportion

#for categorical variable, chiqsquare & t-distribution
#svyglm for categorical need to imput more staff inside the arguments.

#what the difference for using different implutation variable, should be relative to the enrollment size. 
```


```{r}
table(school$c0174, school$fr_size)
prop.table(table(school$c0174, school$fr_size), margin = 2)
chisq.test(table(school$c0174, school$fr_size))

svytable(~c0174 + fr_size, design = new_design)
prop.table(svytable(~c0174 + fr_size, design = new_design), margin = 2)
svyby(formula = ~c0174, by = ~fr_size, design = new_design, FUN = svymean)

```

```{r}
rep_design <- svrepdesign(variables = school[,-c(201:251)],
                          repweights = school[, 202:251],
                          weights = school[,201],
                          combined.weights = TRUE,
                          type = "JKn", scale = 1, rscales = 1)
#subset rows which are only middle schools and high school 
hs_design <- subset(rep_design, strata>300 & strata<400) 
svymean(~vioinc08, hs_design)
true_total <- svytotal(~vioinc08, hs_design)
true_total

library(dplyr)
df <- school %>% filter(strata > 300 & strata < 400)
sum(df$vioinc08)
sum(school$vioinc08)

summary(df$strata)
nrow(df)

school %>% filter(strata > 300 & strata < 400) %>% summarise(sum(vioinc08))

a <- svyby(formula = ~vioinc08, by = ~strata, design = hs_design, FUN = svytotal)
a
a$vioinc08 / true_total


summary(school$vioinc08)
#number of incident less than 


svytable(~c0174 + c0178 + strata, design = hs_design)
prop.table(svytable(~c0174 + c0176 + strata, design = new_design), margin = 2)
svyby(formula = ~c0174, by = ~fr_size, design = new_design, FUN = svytotal)


?svyglm()
fit <- svyglm(vioinc08 ~ factor(c0174) + factor(c0176) + factor(c0178) + factor(c0180), design = hs_design)
summary(fit)







```




